flowchart TD

    User <--> Nginx

    %% CentOS boundary
    subgraph CentOS_boundary ["CentOS 7.6"]

        Nginx(Nginx) --- Client
        Nginx --- ClientProxy1
        Nginx --- ClientProxy2
        Nginx --- ClientProxy3
        Nginx --- ClientProxy4
        Nginx --- API

        %% Docker Engine boundary
        subgraph Docker_boundary ["Docker Engine"]

            %% Docker container boundaries
            subgraph 1 ["nginx:alpine"]
                Client(Client)
            end
            subgraph 2 ["node:15.11"]
                API(API)
            end
            subgraph 3a ["node:15.11"]
                ClientProxy1(Proxy)
            end     
            subgraph 3b ["node:15.11"]
                ClientProxy2(Proxy)
            end     
            subgraph 3c ["node:15.11"]
                ClientProxy3(Proxy)
            end    
            subgraph 3d ["node:15.11"]
                ClientProxy4(Proxy)
            end                                 
            subgraph 4 ["node:15.11"]
                ApiProxy(Proxy)
            end
            subgraph 5 ["docker.elastic.co/elasticsearch/elasticsearch:7.10.2"]
                Elasticsearch[(Elasticsearch)]
            end     
            subgraph 6 ["mongo:4.4.3"]
                Mongo[(Mongo)]
            end    
            subgraph 7 ["src/services/postgis"]
                PostGIS[(PostGIS)]
            end
            subgraph 8 ["osgeo/gdal:latest"]
                GDAL(GDAL)
            end

            %% Topology
            API --- ApiProxy
            API --- Mongo
            API --- PostGIS
            API --- GDAL
            ApiProxy --- Elasticsearch

        end

  
    end