flowchart TD
  subgraph client ["catalogue.saeon.ac.za"]
      _client("React.js static website")
  end

  subgraph gql_public ["GQL Playground (public)"]
    api.catalogue.saeon.ac.za/graphql
  end

subgraph gql_internal ["GQL Playground (internal)"]
    api.catalogue.saeon.int:5002/graphql
  end
  
  subgraph api ["api.catalogue.saeon.ac.za"]
      _api("Node.js application")
      _internal_proxy("AnyProxy")
      _mongo("MongoDB")
      _postgis("PostGIS")
      _gdal("GDAL")
      _elasticsearch("Elasticsearch")

      _api --- _internal_proxy
      _api --- _mongo
      _api --- _gdal
      _api --- _postgis
      _internal_proxy --- _elasticsearch
  end

  subgraph public_proxy ["proxy.catalogue.saeon.ac.za"]
      _nginx("Nginx load balancer")
      _nginx --- _proxy_2("AnyProxy")
      _nginx --- _proxy_3("AnyProxy")
      _nginx --- _proxy_4("AnyProxy")
      _nginx --- _proxy_5("AnyProxy")
  end

  _api <====> gql_public
  _api <====> gql_internal
  client <====> _api
  client <==> _nginx


  