flowchart TD
  subgraph client ["catalogue.saeon.ac.za"]
      _client("React.js static website")
  end

  subgraph gql_public ["api.catalogue.saeon.ac.za/graphql"]
    _gql1("GQL Playground (public client served by API)")
  end

  subgraph gql_internal ["api.catalogue.saeon.int:5002/graphql"]
    _gql2("GQL Playground (internal client served by API)")
  end
  
  subgraph api ["api.catalogue.saeon.ac.za"]
      _api("Node.js application")
      _internal_proxy("AnyProxy")
      _mongo("MongoDB")
      _postgis("PostGIS")
      _gdal("GDAL")
      _elasticsearch("Elasticsearch")

      _api --- _internal_proxy
      _api --- _mongo
      _api --- _gdal
      _api --- _postgis
      _internal_proxy --- _elasticsearch
  end

  subgraph public_proxy ["proxy.catalogue.saeon.ac.za"]
      _proxy("Nginx load balancer")
      _proxy --- _proxy_2("AnyProxy")
      _proxy --- _proxy_3("AnyProxy")
      _proxy --- _proxy_4("AnyProxy")
      _proxy --- _proxy_5("AnyProxy")
  end

  gql_internal <===> api
  gql_public <===> api
  client <===> api
  client <===> public_proxy
  