export { default as multiMatch } from './_multi-match.js'
export { default as geoShape } from './_geo-shape.js'
export { default as termsQuery } from './_terms.js'
export { default as idsQuery } from './_ids.js'
export { default as doisQuery } from './_dois.js'
export { default as minScore } from './_min-score.js'
