export const ELASTICSEARCH_ADDRESS = process.env.ELASTICSEARCH_ADDRESS || `http://localhost:9200`
export const ELASTICSEARCH_CATALOGUE_TEMPLATE = 'saeon-odp'
export const ELASTICSEARCH_CATALOGUE_INDEX = `${ELASTICSEARCH_CATALOGUE_TEMPLATE}-search`
