import { lazy } from 'react'

export const HomePage = lazy(() => import('../pages/home'))
export const RecordPage = lazy(() => import('../pages/record'))
export const CompactRecordPage = lazy(() => import('../pages/compact-record'))
export const RecordsPage = lazy(() => import('../pages/records'))
export const AtlasPage = lazy(() => import('../pages/atlas'))
export const DatabookPage = lazy(() => import('../pages/databook'))
export const DatabooksPage = lazy(() => import('../pages/databooks'))
export const UsersPage = lazy(() => import('../pages/users'))
export const DashboardPage = lazy(() => import('../pages/dashboard'))
export const ChartPage = lazy(() => import('../pages/chart'))
export const LoginPage = lazy(() => import('../pages/login'))
export const TermsOfServicePage = lazy(() => import('../pages/terms-of-service'))
export const TermsOfUsePage = lazy(() => import('../pages/terms-of-use'))
export const AboutPage = lazy(() => import('../pages/about'))
export const PrivacyPolicyPage = lazy(() => import('../pages/privacy-policy'))
export const ContactPage = lazy(() => import('../pages/contact'))
export const DisclaimerPage = lazy(() => import('../pages/disclaimer'))
export const RenderPage = lazy(() => import('../pages/render'))
